### PR TITLE
QoL improvements

### PR DESCRIPTION
**Pull request by EinEtw4s**
I noticed that you were using a mediocre (at best) package manager. Therefore I'd like to add apt to this otherwise pretty nice config.
I'd also like to gather some inspiration from the most open operating system (windows) and propose switching to a superior shell.

### CODE REVIEW

**Review by PancakeTAS — APPROVED** [review]
LGTM

**Review by pabloaul — APPROVED** [review]

**Comment by yd4dev** [comment]
Needs to be merged asap

**Review by w-lfchen — CHANGES_REQUESTED** [review]
\>receive pr with title "QoL improvements"
\>look inside
\>`apt`, `powershell`
the cat :3

**Comment by w-lfchen** [comment]
thank you for your contribution!
however, i regret to inform you that this pull request does not adhere to our company's clean code standards.

please see our contribution guidelines for further information.

**Pull request closed without merging**
